### ISSUE TITLE
Error initializing Drizzle - v1.5.3

### ISSUE THREAD

**Issue by theblock-dev** [trufflesuite/drizzle#137]
Getting issue in initializing the Drizzle, the smart contract has been deployed to the local ganache client. 
![image](https://user-images.githubusercontent.com/5169927/161248043-b3c15370-3c99-4196-b6f3-878ed15731fc.png)

![image](https://user-images.githubusercontent.com/5169927/161248069-3d6971aa-8ea3-4db5-873f-fae6f18fb9a2.png)

One thing - why is drizzle trying to  connect to port# 8545. The ganache client is running on 9545. 

![image](https://user-images.githubusercontent.com/5169927/161248213-7fa1ab2a-cbd1-4ced-a0f5-d8695dea1b58.png)

1) drizzleOptions.js 

![image](https://user-images.githubusercontent.com/5169927/161248483-3b59fc1e-a48c-4d5f-867b-e93d7453fb70.png)

**Comment by rsodre** [comment]
You may need to add ganache as fallback:

```
const options = {
	contracts: [CryptoKittens],
	web3: {
		fallback: {
			type: 'ws',
			url: 'ws://127.0.0.1:7545', // the url you see on ganache UI
		},
	},
};
```

**Comment by theblock-dev** [comment]
Thanks, that works.
